version: "2"
linters:
  enable:
    - revive
    - bodyclose
    - contextcheck
    - errname
    - errorlint
    - gocognit
    - gocritic
    - gocyclo
    - goprintffuncname
    - intrange
    - musttag
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wsl_v5
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - hugeParam
        - paramTypeCombine
        - importShadow
    gocyclo:
      min-complexity: 15
    nakedret:
      max-func-lines: 10
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      enable:
        - err
    govet:
      enable:
        - shadow
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - contextcheck
          - noctx
          - usetesting
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
